export interface BankOption {
  code?: string;
  name: string;
  category?: "BUMN" | "Swasta" | "Digital" | "BPD" | "Syariah";
}

export const COMMON_BANKS: string[] = [
  // Bank Utama / BUMN
  "Bank Mandiri",
  "BCA",
  "BRI",
  "BNI",
  "BSI",
  "BTN",

  // Bank Swasta Populer
  "CIMB Niaga",
  "Bank Permata",
  "Bank Danamon",
  "Bank Mega",
  "Bank OCBC NISP",
  "Bank Panin",
  "Maybank Indonesia",
  "Bank Sinarmas",
  "KB Bank (Bank Bukopin)",
  "Bank Muamalat",
  "Bank BTPN",
  "Bank Commonwealth",
  "Bank DBS Indonesia",
  "Bank UOB Indonesia",

  // Bank Digital
  "Bank Jago",
  "SeaBank",
  "Blu by BCA Digital",
  "Bank Neo Commerce (BNC)",
  "Jenius (Bank BTPN)",
  "Allo Bank",
  "Line Bank",
  "Superbank",
  "Bank Raya Indonesia",

  // Bank Pembangunan Daerah (BPD)
  "Bank BJB",
  "Bank DKI",
  "Bank Jateng",
  "Bank Jatim",
  "Bank BPD DIY",
  "Bank Sumut",
  "Bank Nagari",
  "Bank Riau Kepri Syariah",
  "Bank Sumsel Babel",
  "Bank Lampung",
  "Bank Jambi",
  "Bank Bengkulu",
  "Bank Kalbar",
  "Bank Kaltimtara",
  "Bank Kalteng",
  "Bank Sulselbar",
  "Bank SulutGo",
  "Bank Sulteng",
  "Bank Sultra",
  "Bank NTB Syariah",
  "Bank NTT",
  "Bank Maluku Malut",
  "Bank Papua",
];

export const CATEGORIZED_BANKS = {
  BUMN: [
    "Bank Mandiri",
    "BCA",
    "BRI",
    "BNI",
    "BSI",
    "BTN",
  ],
  Swasta: [
    "CIMB Niaga",
    "Bank Permata",
    "Bank Danamon",
    "Bank Mega",
    "Bank OCBC NISP",
    "Bank Panin",
    "Maybank Indonesia",
    "Bank Sinarmas",
    "KB Bank (Bank Bukopin)",
    "Bank Muamalat",
    "Bank BTPN",
    "Bank Commonwealth",
    "Bank DBS Indonesia",
    "Bank UOB Indonesia",
  ],
  Digital: [
    "Bank Jago",
    "SeaBank",
    "Blu by BCA Digital",
    "Bank Neo Commerce (BNC)",
    "Jenius (Bank BTPN)",
    "Allo Bank",
    "Line Bank",
    "Superbank",
    "Bank Raya Indonesia",
  ],
  BPD: [
    "Bank BJB",
    "Bank DKI",
    "Bank Jateng",
    "Bank Jatim",
    "Bank BPD DIY",
    "Bank Sumut",
    "Bank Nagari",
    "Bank Riau Kepri Syariah",
    "Bank Sumsel Babel",
    "Bank Lampung",
    "Bank Jambi",
    "Bank Bengkulu",
    "Bank Kalbar",
    "Bank Kaltimtara",
    "Bank Kalteng",
    "Bank Sulselbar",
    "Bank SulutGo",
    "Bank Sulteng",
    "Bank Sultra",
    "Bank NTB Syariah",
    "Bank NTT",
    "Bank Maluku Malut",
    "Bank Papua",
  ],
};
